version: '3'
services:  
  web-admin:
    container_name: pipeline
    image: pipeline
    ports:
      - 8000:8000
    environment:
      - PORT=8000
    stdin_open: true
    tty: true
    restart: always
    # volumes:
    #   - ../sourcecode:/app