version: '3.0'
services: 
    pipeline:
        container_name: pipeline-demo
        image: pipeline-demo
        ports:
            - 3000:3000
        environment:
            - PORT=3000
        stdin_open: true
        tty: true
        restart: always